### Health Check

GET http://localhost:8080/health
Accept: application/json

### Get Images

GET http://localhost:8080/images
Accept: application/json


### Get Image

GET http://localhost:8080/images/search?tag=%231
Accept: application/json