// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID    pgtype.UUID `json:"id"`
	Title pgtype.Text `json:"title"`
	Tags  pgtype.Text `json:"tags"`
}
