// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getImage = `-- name: GetImage :one
SELECT id, title, tags FROM images
WHERE title = $1 LIMIT 1
`

func (q *Queries) GetImage(ctx context.Context, title pgtype.Text) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, title)
	var i Image
	err := row.Scan(&i.ID, &i.Title, &i.Tags)
	return i, err
}

const listImages = `-- name: ListImages :many
SELECT id, title, tags FROM images
`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.ID, &i.Title, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
