// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetImage(ctx context.Context, title pgtype.Text) (Image, error)
	ListImages(ctx context.Context) ([]Image, error)
}

var _ Querier = (*Queries)(nil)
